#!/bin/bash
num_gpu=2
runai submit \
  --name svhn-recon \
  --image aicregistry:5000/mark:ddpm-ood \
  --backoff-limit 0 \
  --gpu ${num_gpu} \
  --cpu 12 \
  --large-shm \
  --host-ipc \
  --project mark \
  --run-as-user \
  --volume /nfs/home/mark/projects/ddpm-ood/ddpm-ood/:/project/ \
  --volume /nfs/home/mark/projects/ddpm-ood/data:/data/ \
  --volume /nfs/home/mark/projects/ddpm-ood/output/:/output/ \
  --environment data_root=/data \
  --environment output_root=/output \
  --command -- torchrun --nproc_per_node=${num_gpu} --nnodes=1 --node_rank=0 /project/reconstruct.py \ --output_dir=/output/ \
  --model_name=monaigen_svhn_scaledlinear \
  --validation_ids=/data/data_splits/SVHN_val.csv \
  --in_ids=/data/data_splits/SVHN_test.csv \
  --out_ids=/data/data_splits/CIFAR10_test.csv,/data/data_splits/CelebA_test.csv,/data/data_splits/SVHN_vflip_test.csv,/data/data_splits/SVHN_hflip_test.csv \
  --is_grayscale=0 \
  --num_inference_steps=100 \
  --inference_skip_factor=2 \
  --run_val=1 \
  --run_in=1 \
  --run_out=1 \
  --batch_size=256 \
  --first_n_val=2048 \
  --first_n=2048 \
  --prediction_type=epsilon \
  --model_type=small \
  --beta_schedule=scaled_linear \
  --beta_start=0.0015 \
  --beta_end=0.0195
