#!/bin/bash
num_gpu=2
runai submit \
  --name svhn \
  --image aicregistry:5000/mark:ddpm-ood \
  --backoff-limit 0 \
  --gpu ${num_gpu} \
  --cpu 8 \
  --large-shm \
  --host-ipc \
  --project mark \
  --run-as-user \
  --volume /nfs/home/mark/projects/ddpm-ood/ddpm-ood/:/project/ \
  --volume /nfs/home/mark/projects/ddpm-ood/data:/data/ \
  --volume /nfs/home/mark/projects/ddpm-ood/output/:/output/ \
  --environment data_root=/data \
  --environment output_root=/output \
  --command -- torchrun --nproc_per_node=${num_gpu} --nnodes=1 --node_rank=0 /project/train.py \
  --output_dir=/output/ \
  --model_name=monaigen_svhn_scaledlinear \
  --training_ids=/data/data_splits/SVHN_train.csv \
  --validation_ids=/data/data_splits/SVHN_val.csv \
  --is_grayscale=0 \
  --n_epochs=300 \
  --batch_size=256 \
  --eval_freq=10 \
  --checkpoint_every=100 \
  --cache_data=1 \
  --prediction_type=epsilon \
  --model_type=small \
  --beta_schedule=scaled_linear \
  --beta_start=0.0015 \
  --beta_end=0.0195
